# Generated by Django 4.1.6 on 2023-03-05 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_liftingcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiftingCart',
        ),
    ]
