# Generated by Django 4.1.6 on 2023-03-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_liftingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifting',
            name='date',
            field=models.DateField(),
        ),
    ]
