# Generated by Django 4.1.6 on 2023-03-22 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0028_product_qty'),
        ('account', '0005_alter_lifting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('mem_number', models.PositiveIntegerField(unique=True)),
                ('dsr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.dsr')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.product')),
                ('sell_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sellprice')),
            ],
        ),
    ]
