# Generated by Django 4.1.6 on 2023-03-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
