# Generated by Django 4.1.6 on 2023-03-24 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_sales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
