# Generated by Django 4.1.6 on 2023-03-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_sales_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
