# Generated by Django 4.1.6 on 2023-03-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_sales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
