# Generated by Django 4.1.6 on 2023-03-27 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_damage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Damage',
        ),
    ]
