# Generated by Django 4.1.6 on 2023-03-27 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0028_product_qty'),
        ('account', '0020_delete_damage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('mem_number', models.PositiveIntegerField(unique=True)),
                ('qty', models.PositiveIntegerField(default=0)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('purchase_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Purchase_Price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.doprice')),
                ('dsr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.dsr')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.market')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.product')),
                ('sales_Price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sellprice')),
            ],
        ),
    ]
