# Generated by Django 4.1.6 on 2023-03-27 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0028_product_qty'),
        ('account', '0021_damage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='sales_Price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setup.sellprice'),
        ),
    ]
