# Generated by Django 4.1.6 on 2023-03-28 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0028_product_qty'),
        ('account', '0022_alter_damage_sales_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='dsr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.dsr'),
        ),
        migrations.AlterField(
            model_name='damage',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.market'),
        ),
    ]
