# Generated by Django 4.1.6 on 2023-03-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0028_product_qty'),
        ('account', '0023_alter_damage_dsr_alter_damage_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='sales_Price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.sellprice'),
        ),
    ]
