# Generated by Django 4.1.6 on 2023-04-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_acdiccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='acdiccount',
        ),
    ]
