# Generated by Django 4.1.6 on 2023-04-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_dailycost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dailycost',
        ),
    ]
