# Generated by Django 4.1.6 on 2023-04-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_dailycost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='mem_number',
            field=models.PositiveIntegerField(),
        ),
    ]
