# Generated by Django 4.1.6 on 2023-04-12 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_alter_sales_mem_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='dsr',
        ),
        migrations.RemoveField(
            model_name='damage',
            name='market',
        ),
    ]
