# Generated by Django 4.1.6 on 2023-08-19 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0031_collectionsetup'),
        ('account', '0036_remove_damage_dsr_remove_damage_market'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collection_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.collectionsetup')),
            ],
        ),
    ]
