# Generated by Django 4.1.6 on 2023-11-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_collectiontransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shop_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rashed_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bazar_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('milon', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_check', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mehdi_sr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card', models.DecimalField(decimal_places=2, max_digits=10)),
                ('damage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('naitrogen_damage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('robiul_sr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pubali_bank', models.DecimalField(decimal_places=2, max_digits=10)),
                ('robiul_dsr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
