# Generated by Django 4.1.6 on 2023-02-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_dsr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('account_no', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=50)),
                ('account_type', models.CharField(choices=[('Deposit', 'Deposit A/c'), ('CC', 'CC A/c')], default='Deposit', max_length=10)),
            ],
        ),
    ]
