# Generated by Django 4.1.6 on 2023-02-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
