# Generated by Django 4.1.6 on 2023-02-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='Supplier',
        ),
    ]
