# Generated by Django 4.1.6 on 2023-02-18 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0016_delete_dorate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DORate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='setup.product')),
            ],
        ),
    ]
