# Generated by Django 4.1.6 on 2023-02-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0017_dorate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DORate',
        ),
    ]
