# Generated by Django 4.1.6 on 2023-02-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0021_dorate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dorate',
        ),
    ]
