# Generated by Django 4.1.6 on 2023-02-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0025_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
