# Generated by Django 4.1.6 on 2023-03-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0026_delete_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='Doprice',
        ),
    ]
