# Generated by Django 4.1.6 on 2023-08-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0030_discountsetup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collectionsetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
